# @package _global_

# specify here default training configuration
defaults:
  - trainer: cpu.yaml
  - finetune_trainer: minimal.yaml
  - model: entity_marker_baseline.yaml
  - data: drugprot.yaml
  - callbacks: default.yaml # set this to null if you don't want to use callbacks
  - logger: wandb # set logger here or use command line (e.g. `python run.py logger=wandb`)
  - experiment: null
  - hparams_search: null

  - hydra: default.yaml


# path to original working directory
# hydra hijacks working directory by changing it to the current log directory,
# so it's useful to have this path as a special variable
# learn more here: https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
work_dir: ${hydra:runtime.cwd}

# path to folder with data
data_dir: ${work_dir}/data/

# use `python run.py debug=true` for easy debugging!
# this will run 1 train, val and test loop with only 1 batch
# equivalent to running `python run.py trainer.fast_dev_run=true`
# (this is placed here just for easier access from command line)
debug: False


# pretty print config at the start of the run using Rich library
print_config: True

# disable python warnings if they annoy you
ignore_warnings: True

batch_size: 8
optimized_metric: val/f1
